<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array (
		'key' => 'group_57548fee3d8a4',
		'title' => 'Content Options',
		'fields' => array (
			array (
				'key' => 'field_5758bd788adbe',
				'label' => 'Youtube Video Overlay',
				'name' => 'youtube_video_overlay',
				'type' => 'image',
				'instructions' => 'Max Width: 256px, Max Height: 64px',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '256',
				'max_height' => '64',
				'max_size' => '',
				'mime_types' => '',
				),
			array (
				'key' => 'field_57548ff33c6b7',
				'label' => 'Phone Numbers',
				'name' => 'phone_numbers',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'collapsed' => '',
				'min' => '',
				'max' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
				'sub_fields' => array (
					array (
						'key' => 'field_575490113c6b8',
						'label' => 'Location',
						'name' => 'location',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 50,
							'class' => '',
							'id' => '',
							),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
						),
					array (
						'key' => 'field_575490283c6b9',
						'label' => 'Phone Number',
						'name' => 'phone_number',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => 50,
							'class' => '',
							'id' => '',
							),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
						'readonly' => 0,
						'disabled' => 0,
						),
					),
				),
			array (
				'key' => 'field_57549071bc8bc',
				'label' => 'Contact Email',
				'name' => 'contact_email',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				),
			array (
				'key' => 'field_5754903dbc8bb',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'google_map',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
				),
			array (
				'key' => 'field_57549576b84d8',
				'label' => 'Main Website URL',
				'name' => 'main_website_url',
				'type' => 'url',
				'instructions' => 'Starts with http://',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
					),
				'default_value' => '',
				'placeholder' => '',
				),
			),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-content-options',
					),
				),
			),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		));

endif;
